 var miApp = angular.module('agenda', [])
        miApp.controller('controlador2', ['$scope', function ($scope) {
            $scope.agenda = [
              { area: "RECTORIA", cargo: "Operadora", tel: "6701" },
                { area: "RECTORIA", cargo: "Rector", tel: "6702" },
                { area: "RECTORIA", cargo: "Secretaria del Rector", tel: "6703" },
                { area: "RECTORIA", cargo: "Asesor del Rector", tel: "6787" },
                { area: "RECTORIA", cargo: "Dpto. Marxismo Leninismo e Historia", tel: "6818" },
                { area: "RECTORIA", cargo: "Dpto. Planificacion", tel: "6785" },
                { area: "RECTORIA", cargo: "Secretaria General", tel: "6728" },
                { area: "RECTORIA", cargo: "Secretaria", tel: "6752" },
                { area: "RECTORIA", cargo: "Dpto. de Maestria y Especialidades", tel: "6902" },
                { area: "RECTORIA", cargo: "Auditores", tel: "6750" },
                { area: "RECTORIA", cargo: "OCIC", tel: "6718" },
                { area: "RECTORIA", cargo: "Doctorado", tel: "6878" },
                { area: "VICERRECTORIA DOCENTE", cargo: "Vicerrectora Docente", tel: "6704" },
                { area: "VICERRECTORIA DOCENTE", cargo: "Secretaria de VRD", tel: "6705" },
                { area: "VICERRECTORIA DOCENTE", cargo: "Departamento de Universalizacion", tel: "6722" },
                { area: "VICERRECTORIA INVESTIGACION Y POSTGRADO", cargo: "Departamento de Postgrado", tel: "6800" },
                { area: "VICERRECTORIA INVESTIGACION Y POSTGRADO", cargo: "Centro de Estudio (CEDE)", tel: "6790" },
                { area: "DEPARTAMENTO DE CUADRO", cargo: "Direccion de Cuadro", tel: "6721" },
                { area: "DEPARTAMENTO DE INGRESO", cargo: "Jefe de Dpto. Ingreso", tel: "6764" },
                { area: "DEPARTAMENTO DE INGRESO", cargo: "Area de Atencion 30", tel: "6864" },
                { area: "DEPARTAMENTO DE INGRESO", cargo: "Oficina de Guardia", tel: "6859  " },
                { area: "DEPARTAMENTO DE INGRESO", cargo: "Departamento de Proteccion Fisica", tel: "6830" },
                { area: "RECURSOS HUMANOS", cargo: "Direccion Recursos Humanos", tel: "6754" },
                { area: "RECURSOS HUMANOS", cargo: "Departamento de Fuerza de Trabajo", tel: "6770" },
                { area: "RECURSOS HUMANOS", cargo: "Departamento de Cuadro (Recursos Humanos)", tel: "6756" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Vicerrector Economico", tel: "6710" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Secretaria de la Direccion Economica", tel: "6730" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Departamento de Estadistica", tel: "6901" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Departamento de Contabilidad", tel: "6761" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Departamento de Nomina", tel: "6762" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Caja Central", tel: "6905" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Direccion ATM", tel: "6832" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Oficina Comercial", tel: "6824" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Almacen ATM", tel: "6863" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Cheque", tel: "6760" },
                { area: "VICERRECTORIA ECONOMICA", cargo: "Contrato", tel: "6892" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Vicerrector Admin. y Servicios", tel: "6708" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Secretaria VRAS", tel: "6871" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Asesor Relaciones Internacionales", tel: "6871" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Servicio Academico Internacional", tel: "6847" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Direccion de Alimentacion", tel: "6823" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Cocina Comedor", tel: "6826" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Almacenes de Viveres", tel: "6866" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Direccion de Transporte", tel: "6833" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Gasolinera", tel: "6834" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Jefe de Transporte", tel: "6904" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Imprenta", tel: "6831" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Almacen de Texto", tel: "6791" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Edificio de Aulas D-1", tel: "6813" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Edificio de Aulas D-2", tel: "6759" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Edificio de Aulas D-3", tel: "6749" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Direccion de Inversiones", tel: "6733" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Especialista Principal", tel: "6751" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Jefe de Mantenimiento Especializado", tel: "6827" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Secretaria del Jefe de Mtto. Espec.", tel: "6828" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "Mantenimiento Constructivo", tel: "6829" },
                { area: "VICERRECTORIA ADMINISTRACION", cargo: "MININT", tel: "6825" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Decana de la Facultad", tel: "6715" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Secretaria de la Decana", tel: "6773" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Secretaria de la Facultad", tel: "6816" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Administradora de la Facultad", tel: "6810" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Vicedecano Docente", tel: "6853" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Vicedecano Universalizacion", tel: "6779" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Departamento de Español", tel: "6854" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Departamento de Estudio Sociocultural", tel: "6846" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Departamento de Comunicacion Social ", tel: "6850" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Departamento Lengua Inglesa", tel: "6875" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Marxismo", tel: "6818" },
                { area: "FACULTAD DE HUMANIDADES", cargo: "Vicedecano de Investigacion", tel: "6836" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Decano de la Facultad", tel: "6792" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Vicedecano Docente", tel: "6869" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Secretaria de la Facultad", tel: "6843" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Laboratorio de Informatica", tel: "6868" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Departamento de Informatica", tel: "6856" },
                { area: "FACULTAD DE INFORMATICA", cargo: "Departamento de Matematica", tel: "6782" },
                { area: "CENTRO DE INFORMACION", cargo: "Direccion del CICT", tel: "6788" },
                { area: "CENTRO DE INFORMACION", cargo: "Departamento CICT", tel: "6872" },
                { area: "CENTRO DE INFORMACION", cargo: "Biblioteca", tel: "6789" },
                { area: "CENSEIC", cargo: "Director del CENSEIC", tel: "6876" },
                { area: "CENSEIC", cargo: "Secretaria del Director", tel: "6877" },
                { area: "CENSEIC", cargo: "Local del Grupo de Redes", tel: "6857" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Administradora de la Facultad", tel: "6893" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Jefe Departamento Gabinete", tel: "6891" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Vicedecano Investigacion", tel: "6895" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Vicedecano Universalizacion", tel: "6892" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Departamento de Industrial", tel: "6777" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Vicedecano Docente", tel: "6886" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Departamento Tecnica de Direccion", tel: "6893" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Departamento de Economia", tel: "6849" },
                { area: "FACULTAD INDUSTRIAL ECONOMIA", cargo: "Departamento de Contabilidad y Finanzas", tel: "6844" },
                { area: "RESIDENCIA ESTUDIANTIL", cargo: "Administrador Residencia Estudiantil", tel: "6817" },
                { area: "RESIDENCIA ESTUDIANTIL", cargo: "Consulta Medica", tel: "6867" },
                { area: "RESIDENCIA ESTUDIANTIL", cargo: "Enfermeria", tel: "6814" },
                { area: "RESIDENCIA ESTUDIANTIL", cargo: "Estomatologia", tel: "6815" },
                { area: "RESIDENCIA ESTUDIANTIL", cargo: "Correo", tel: "261997" },
                { area: "ORGANIZACIONES POLITICAS", cargo: "UJC", tel: "6819" },
                { area: "ORGANIZACIONES POLITICAS", cargo: "FEU", tel: "6820" },
                { area: "FACULTAD CULTURA FISICA", cargo: "Secretaria del Decano", tel: "6797" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Decano de la Facultad", tel: "6726" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Secretaria del Decano", tel: "6727" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Secretaria de la Facultad", tel: "6765" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Vicedecano Docente", tel: "6709" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Administradora de la Facultad", tel: "6771" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Laboratorio de Microbiologia", tel: "6767" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Vicedecano Investigacion", tel: "6896" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Jefe Departamento Agricultura", tel: "6768" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Jefe Departamento Agronomia", tel: "6847" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Departamento Agricultura", tel: "6848" },
                { area: "FACULTAD DE AGRONOMIA", cargo: "Departamento Ciencias Quimicas", tel: "6897" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Decana de la Facultad", tel: "6723" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Secretaria de la Decana", tel: "6781" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Vicedecano Investigacion y Postgrado", tel: "6882" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Vicedecano Docente", tel: "6879" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Departamento Ingenieria Mecanica", tel: "6783" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Laboratorio de Fisica", tel: "6794" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Jefe del Departamento de Quimica", tel: "6786" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Departamento de Quimica", tel: "6880" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Laboratorio de Quimica", tel: "6793" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Jefe del Departamento de Mecanica", tel: "6851" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Departamento de Quimica", tel: "6881" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Laboratorio de Dibujo", tel: "6903" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Departamento de Fisica", tel: "6809" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Departamento de Fisica", tel: "6725" },
                { area: "FACULTAD QUIMICA MECANICA", cargo: "Vicedecano Universalizacion", tel: "6884" }
            ]
        }])